#!/usr/bin/env ruby
# encoding: UTF-8
require 'yaml'
require 'pathname'
require 'cgi'

Encoding.default_external = Encoding::UTF_8

ROOT = Pathname(ENV.fetch('FOOD_ROOT', '/Users/jaredlandt/Documents/Home/Food'))
COOKBOOK = ROOT.join('CookBook')
DOCS = ROOT.join('Documentation')

Recipe = Struct.new(:title, :filename, :equipment, :tags, :protein, keyword_init: true)

def load_recipes
  Dir[COOKBOOK.join('*.md')].map do |path|
    text = File.read(path)
    next unless text.start_with?('---')
    if text =~ /\A---\s*\n(.*?)\n---\s*\n/m
      data = YAML.safe_load(Regexp.last_match(1)) || {}
      Recipe.new(
        title: data['title'] || File.basename(path, '.md'),
        filename: Pathname(path).basename,
        equipment: data['equipment'] || [],
        tags: data['tags'] || [],
        protein: data['protein'] || 'other'
      )
    end
  end.compact
end

def markdown_link(recipe)
  encoded = CGI.escape(recipe.filename.to_s).gsub('+', '%20')
  "[#{recipe.title}](../CookBook/#{encoded})"
end

def display_equipment(key)
  key.to_s.tr('_', ' ')
end

def build_equipment_inventory(recipes)
  equipment_map = Hash.new { |h, k| h[k] = [] }
  recipes.each do |recipe|
    recipe.equipment.each { |eq| equipment_map[eq] << recipe }
  end

  lines = []
  lines << "# Equipment Inventory"
  lines << ""
  lines << "_Generated by `scripts/food/generate_docs.rb` from cookbook metadata._"
  lines << ""
  lines << "Mark status: `✅` have, `🛒` need, `?` unsure."
  lines << ""
  lines << "| equipment | recipes | status | linked list |"
  lines << "| --- | --- | --- | --- |"

  equipment_map.sort_by { |eq, recs| [-recs.size, eq] }.each do |equipment, recs|
    links = recs.sort_by(&:title).map { |r| markdown_link(r) }.join(', ')
    lines << "| #{display_equipment(equipment)} | #{recs.size} |  | #{links} |"
  end
  lines.join("\n") + "\n"
end

def build_recipes_index(recipes)
  to_heading = ->(protein) { protein.to_s.split('_').map(&:capitalize).join(' ') }

  lines = []
  lines << "# Recipes Index"
  lines << ""
  lines << "_Generated by `scripts/food/generate_docs.rb` from cookbook metadata._"
  lines << ""
  lines << "## By Protein"

  protein_order = %w[chicken turkey beef pork seafood vegetarian optional_meat other]
  grouped = recipes.group_by { |r| r.protein || 'other' }
  protein_order.each do |protein|
    next unless grouped[protein]&.any?
    lines << ""
    lines << "### #{to_heading.call(protein)}"
    grouped[protein].sort_by(&:title).each do |recipe|
      tag_line = recipe.tags.any? ? " — tags: #{recipe.tags.join(', ')}" : ""
      lines << "- #{markdown_link(recipe)}#{tag_line}"
    end
  end

  other_keys = (grouped.keys - protein_order)
  other_keys.sort.each do |protein|
    lines << ""
    lines << "### #{to_heading.call(protein)}"
    grouped[protein].sort_by(&:title).each do |recipe|
      tag_line = recipe.tags.any? ? " — tags: #{recipe.tags.join(', ')}" : ""
      lines << "- #{markdown_link(recipe)}#{tag_line}"
    end
  end

  lines.join("\n") + "\n"
end

def write_docs
  recipes = load_recipes
  equipment_md = build_equipment_inventory(recipes)
  index_md = build_recipes_index(recipes)

  DOCS.join('Equipment Inventory.md').write(equipment_md)
  DOCS.join('Recipes Index.md').write(index_md)
end

write_docs
